feat: enforce 0.01 lower bound for widthTolerance
imgix/imgix-core-js pull request #211
Opened 2021-01-20 23:51 UTC by ericdeansanchez

The purpose of this PR is to enforce a lower bound on `widthTolerance`.
Prior, `widthTolerance` was expected to be greater than zero. However,
accepting a number like `0.000000001` here can do more harm than good.
We don't expect that such a number represents an actual use-case,
rather, we're enforcing this lower bound to keep defaults sensible and
help users guard against undesirable/accidental input.

Now, we enforce a lower bound of `0.01` on `widthTolerance`. This is also
pretty lenient, e.g. with the min/max width defaults set and setting the width
tolerance down to `0.01` (to one percent) we can make a srcset with 224
image URLs in it where the widths progress like `100, 102, 104, 106,
108, 110...`.

2021-01-21 06:55 UTC, sherwinski requested changes

2021-01-21 06:55 UTC, sherwinski commented on test/test-buildSrcSet.mjs
> +          assert.strictEqual(actualLength, 2);
Can we include a test ensuring that these values are the min and max?

2021-01-21 08:52 UTC, frederickfogerty approved these changes
LGTM ✌️ I'm wondering if it's worthwhile also bounding `widthTolerance` to be at max `1` as well

2021-01-21 19:56 UTC, sherwinski approved these changes

2021-01-21 20:08 UTC, merged

2021-02-03 00:09 UTC, ericdeansanchez commented
:tada: This PR is included in version 0.3.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/imgix-core-js/v/0.3.0-beta.1)
- [GitHub release](https://github.com/imgix/imgix-core-js/releases/tag/v0.3.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: